# Generated by Django 5.2 on 2025-04-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HegazyAPP', '0002_team_rename_match_date_match_match_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='home_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(default='مستقبل', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='team_logos/'),
        ),
        migrations.AlterField(
            model_name='match',
            name='location',
            field=models.CharField(default='غير محدد', max_length=100),
        ),
    ]
