# Generated by Django 5.2 on 2025-04-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HegazyAPP', '0003_match_away_score_match_home_score_match_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
